### ISSUE TITLE
Translation to Brazilian Portuguese (pt-BR) required

### ISSUE THREAD

**Issue by samuelfmlourenco** [bloguetronica/itusb2-mngr#3]
A Brazilian Portuguese (pt-BR) translator is required to translate this application. In order to avoid dictionary translations (unfortunately, many "translators" just use the online dictionary), I'm adamant that the translator must speak the Brazilian variant fluently. Also, I prefer translations that follow the rules in Brazil prior to the Acordo Ortográfico (pre-AO). This is so, because the European Portuguese translation doesn't embrace the Acordo Ortográfico as well. This translation will be used for the international version as well.

There is already a European Portuguese (pt-PT) available. However, you don't have to follow it to the letter. Just use it as a guideline, if you prefer. It is far more important to convey and preserve the meaning of the messages. The English version is the original.

You should use Qt Linguist, preferably the version that comes with Qt Creator 4.11.0 (which is based on Qt 5.12.8). Please, don't submit a direct pull request. First let me check and correct (align) the .ts file you will provide to me (basically, I'll check it for compatibility with Qt 5.12.8). Either I'll send it you back and/or arrange for you to submit to the next version's branch. Mind that we never work on the main branch. Be assured, that my objective is for you to submit the sanctioned version of the file, so you can keep the credit. Your name will be featured on the "Authors" file as well (but not on the About box, because that presents major challenges).

Thanks in advance! Your contribution will be valuable!

**Comment by renato04** [comment]
Hello!
How can I generate this `.qm` file?
Can I just translate the xml file?

**Comment by samuelfmlourenco** [comment]
> Hello! How can I generate this `.qm` file? Can I just translate the xml file?

Hi! Thanks for your interest. The ".qm" file is a binary generated once the translation is complete. I'll do the generation. You should use the ".ts" file, in this case "itusb2-mngr_pt_BR.ts". This will require Qt Linguist, preferably on Linux, because of the line endings. Editing the ".ts" file by hand is not recommended.

**Comment by samuelfmlourenco** [comment]
Will not be applied.
